STEAM_API_KEY: '572CCDDED77DD8694500800177388F9E'
APP_LIST_STEAM_API_URL: 'http://api.steampowered.com/ISteamApps/GetAppList/v0002/?key=572CCDDED77DD8694500800177388F9E&format=json'
APP_DETAIL_STEAM_API_URL: 'https://store.steampowered.com/api/appdetails?appids='